[build]
  publish = "WTM_project/dist"
  command = "npm run build"


[dev]
  command = "npm run dev"
  port = 3000
  framework = "vite"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[functions]
  directory = "netlify/functions"